/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_hackcode_ProxyApplication */

#ifndef _Included_org_hackcode_ProxyApplication
#define _Included_org_hackcode_ProxyApplication
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     org_hackcode_ProxyApplication
 * Method:    start
 * Signature: (Landroid/app/Application;Ljava/lang/String;Ljava/lang/ClassLoader;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_org_hackcode_ProxyApplication_start
  (JNIEnv *, jobject, jobject, jstring, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
